name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile hold-to-lean/main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: main-executable-${{ matrix.os }}
        path: dist/main